import { NextResponse } from "next/server";
import { getServerSession } from "next-auth";
import { authOptions } from "@/lib/auth";
import { getOctokitClient } from "@/lib/github/octokit";
import { commitFilesToRepo, createPullRequestWithFiles } from "@/lib/github/push";
import { pushReadmeSchema } from "@/lib/validation/generate-schema";

export const dynamic = "force-dynamic";

export async function POST(req: Request) {
  try {
    const session = await getServerSession(authOptions);
    const userAccessToken = session?.user?.accessToken;

    if (!userAccessToken) {
      return NextResponse.json(
        {
          error:
            "Authentication required. Please sign in with your GitHub account with write permissions to push to repositories.",
        },
        { status: 401 }
      );
    }

    const body = await req.json();
    const parsed = pushReadmeSchema.safeParse(body);
    if (!parsed.success) {
      return NextResponse.json(
        { error: "Validation failed", details: parsed.error.flatten() },
        { status: 400 }
      );
    }

    const { repoUrl, readmeContent, licenseContent, mode, commitMessage } = parsed.data;

    const match = repoUrl.match(/github\.com\/([^/]+)\/([^/#?]+)/);
    if (!match) {
      return NextResponse.json(
        { error: "Invalid GitHub URL format." },
        { status: 400 }
      );
    }

    const owner = match[1];
    const repo = match[2].replace(/\.git$/, "");
    const octokit = getOctokitClient(userAccessToken);

    const filesToPush = [{ path: "README.md", content: readmeContent }];
    if (licenseContent && licenseContent.trim().length > 0) {
      filesToPush.push({ path: "LICENSE", content: licenseContent });
    }

    if (mode === "direct-commit") {
      const result = await commitFilesToRepo(octokit, {
        owner,
        repo,
        files: filesToPush,
        commitMessage: commitMessage || "docs: update README.md via ReadmeForge",
      });

      return NextResponse.json({
        success: true,
        mode: "direct-commit",
        commitSha: result.commitSha,
        htmlUrl: result.htmlUrl,
        message: `Successfully committed ${filesToPush.map((f) => f.path).join(" and ")} directly to repository!`,
      });
    } else {
      const prTitle = commitMessage || "docs: synchronize README.md and documentation via ReadmeForge";
      const prBody = `## 🛠️ ReadmeForge Automated Documentation PR\n\nThis pull request updates the repository documentation with comprehensive, human-grade technical documentation generated by **ReadmeForge**.\n\n### Changes Included\n- Updated \`README.md\`\n${licenseContent ? "- Synchronized `LICENSE` file\n" : ""}\n---\n*Forged with [ReadmeForge](https://github.com/Bavly-Hamdy/ReadmeForge)*`;

      const result = await createPullRequestWithFiles(octokit, {
        owner,
        repo,
        files: filesToPush,
        prTitle,
        prBody,
      });

      return NextResponse.json({
        success: true,
        mode: "pull-request",
        prNumber: result.prNumber,
        htmlUrl: result.htmlUrl,
        message: `Successfully opened Pull Request #${result.prNumber}!`,
      });
    }
  } catch (error: unknown) {
    const message = error instanceof Error ? error.message : "Failed to push documentation to GitHub";
    console.error("[GitHub Push README Error]:", error);

    const status = (error as any)?.status ?? 500;
    return NextResponse.json(
      { error: `GitHub API error: ${message}` },
      { status: status === 403 || status === 401 ? status : 500 }
    );
  }
}
