import { GoogleGenerativeAI } from "@google/generative-ai";
import { RepoDigest, ReadmeGenerationParams } from "@/types/repo-digest";

const apiKey = process.env.GEMINI_API_KEY;
if (!apiKey) {
  console.warn("[Gemini AI] Warning: GEMINI_API_KEY environment variable is missing.");
}

export const genAI = new GoogleGenerativeAI(apiKey || "dummy-key");

const CANDIDATE_MODELS = [
  "gemini-1.5-flash-latest",
  "gemini-1.5-pro-latest",
  "gemini-1.5-flash",
  "gemini-1.5-pro",
  "gemini-2.0-flash-exp",
];

/**
 * Robust content generation helper with model fallback list
 */
export async function generateContentWithFallback(prompt: string, systemInstruction?: string): Promise<string> {
  let lastError: unknown = null;

  for (const modelName of CANDIDATE_MODELS) {
    try {
      const model = genAI.getGenerativeModel({
        model: modelName,
        ...(systemInstruction ? { systemInstruction } : {}),
      });

      const result = await model.generateContent(prompt);
      return result.response.text();
    } catch (err) {
      console.warn(`[Gemini AI] Model '${modelName}' unavailable, trying next candidate...`, err);
      lastError = err;
    }
  }

  throw lastError || new Error("All Gemini model candidates failed.");
}

/**
 * Generates an engineering-grade README.md following clean, minimalist technical writing standards.
 */
export async function generateReadmeFromDigest(
  params: ReadmeGenerationParams
): Promise<string> {
  const {
    digest,
    persona = "PORTFOLIO",
    teamName,
    demoUrl,
    customTitle,
    collaborators = [],
  } = params;

  const masterSystemPrompt = `
SYSTEM PROMPT — ENGINEERING-GRADE README GENERATOR

You are a Principal Software Architect producing technical documentation for a software repository.
Write clean, rigorous, highly professional engineering documentation.

STRICT TONE RULES:
- ZERO AI WATERMARKS: Do NOT include phrases like "Generated by AI", "Powered by Gemini AI", or magic sparkles emojis (✨, 🤖, 🪄).
- Focus on technical precision, architecture decisions, clear setup instructions, and clean markdown layout.

INPUT DATA:
${JSON.stringify(digest, null, 2)}

EXTRA METADATA:
- Custom Title: ${customTitle || digest.repoName}
- Persona Selected: ${persona}
- Team / Organization: ${teamName || "Engineering Team"}
- Live Demo URL: ${demoUrl || "N/A"}
- Collaborators / Team Members: ${JSON.stringify(collaborators, null, 2)}

PERSONA SPECIFIC GUIDELINES:
- PORTFOLIO MODE: Focus on architectural decisions, problem statement & core outcomes, screenshots placeholders, and Architectural Decision Records (ADR).
- OPEN_SOURCE MODE: Focus on an All-Contributors HTML avatar grid, Contributing guidelines, Code of Conduct link, and Issue/PR templates guide.
- MINIMALIST MODE: Strip to: Header, Badges, 1-line description, install, run, license. Target under 60 lines.
- ENTERPRISE MODE: Comprehensive API Endpoint Matrix, Security & Compliance policy, Deployment Matrix, Environment specification.

MANDATORY SECTIONS:
1. HERO HEADER:
   - #${customTitle || digest.repoName}
   - Concise tagline
   - Shields.io Badges (style=for-the-badge).
2. TABLE OF CONTENTS: Linked anchor list.
3. OVERVIEW & KEY FEATURES: Technical feature grid.
4. 🏗️ SYSTEM ARCHITECTURE & DATA FLOW:
   - Must include a multi-subgraph Mermaid diagram in a \`\`\`mermaid code block using subgraphs (e.g. \`subgraph Client_Layer["Client & Presentation"]\`, \`subgraph Server_Core["API & Application Logic"]\`, \`subgraph Database_Layer["Data & Persistence"]\`).
   - Architectural Decision Records (ADR) section.
5. 📂 DIRECTORY STRUCTURE: ASCII tree layout.
6. ⚡ GETTING STARTED: Prerequisites, Clone, .env Setup, Install, and Run commands.
7. 🔌 API ENDPOINTS MATRIX (if routes exist): Method | Path | Description.
8. 👥 TEAM & COLLABORATORS: If collaborators list is provided, generate an All-Contributors HTML avatar table (<img src="https://github.com/<handle>.png?size=100" width="60px" />).
9. LICENSE.

OUTPUT FORMAT: Return ONLY valid GitHub-Flavored Markdown (GFM).
`;

  const prompt = `Generate the final engineering README.md for "${customTitle || digest.repoName}".`;
  return await generateContentWithFallback(prompt, masterSystemPrompt);
}
